"""The fake-factor tables of the SM 2018 measurement: per channel and TauFakeFactors process the split, the binning,
fits and --suggest-binning options of the fake factors, the non-closures (in their order) and the DR->SR correction,
and of the process fractions.

Generated by scripts/make_ff_tables.py from TauFakeFactors' resolved configuration /work/jvoss/FF_Updated/configs/non_res_HH/2018; do not
edit. One change against it: the et/mt fraction split has the n_jets edges [-0.5, 2.5, 22.5] of its categories
<=2 and >=3 (U4).
"""
# Configuration files (sha256):
#   common_settings.yaml 58f2f204a342727c1b32b5c2b327e6cf955d4ba6f4aec552484f2bfbbb6375a9
#   corrections_et.yaml de263cc9393f2cb13b82402f72e2cc60f52e25a344b7434840346c2e8388a029
#   corrections_mt.yaml e41b36f54848fe28c10f44e080d84b1733edff7a4651e607e3219131831fd92c
#   corrections_tt.yaml 8327df1feefe92c16c9232b1bf521302fab7c94cbc152156a54b374f0e08e2bb
#   fake_factors_et.yaml 6cc00e7ebaf42dbdfd7e54be33bb8cc254d8fc0f6968610da8ba7b20ae9df852
#   fake_factors_mt.yaml 4242653cd2a10054e88cab69680f1cd72e297e8a31c10a1b59b81eb59f0e1672
#   fake_factors_tt.yaml 5158e2db1e437e19eb3b4f734f90f5e0d4d42182a8e86f631967f75fea2fa628
#   preselection_et.yaml 79c9497f2a2d80a2a5653cc16512aa1e10ac61bd3dcca6b4f5467759a34fe9e9
#   preselection_mt.yaml 519d743140edbbdc8db19345064474283350937bc439788d0b3cc6615c8a9b88
#   preselection_tt.yaml 41aa5306d35999f8abd45ce0df8d4dde3cb8a6380372017815b033744071e631
from shapesmith.measurements.fake_factors import Binned, Equipopulated, Fit, Split

TABLES = {
    "et": {
        "QCD": {
            "split": Split("n_jets", (1.5, 22.5)),
            "fake_factors": Binned("pt_2", ((20.0, 34.7, 41.9, 54.56, 150.0),), (Fit("smoothed", 26.0),), Equipopulated((4,), 20.0, 150.0, 2)),
            "non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5),), (Fit("binwise"),)),
                Binned("pt_1", ((25.0, 40.76, 48.9, 61.11, 81.6, 150.0),), (Fit("smoothed", 15.0, binwise_left=1),), Equipopulated((5,), 25.0, 150.0, 2)),
                Binned("met", ((0.0, 13.27, 22.56, 35.23, 56.98, 150.0),), (Fit("smoothed", 25.0),), Equipopulated((5,), 0.0, 150.0, 2)),
                Binned("mt_tot", ((20.0, 67.33, 92.74, 114.16, 141.42, 250.0),), (Fit("smoothed", 25.0),), Equipopulated((5,), 20.0, 250.0, 2)),
                Binned("iso_1", ((0.0, 5e-05, 0.00727, 0.013649, 0.024915, 0.043362, 0.15),), (Fit("smoothed", 0.02, binwise_left=1),), Equipopulated((5,), 5e-05, 0.15, 6, add_left=(0.0,))),
            ),
            "dr_sr": Binned("pt_tautau", ((0.0, 48.12, 71.36, 92.45, 114.57, 150.0),), (Fit("smoothed", 20.0),), Equipopulated((5,), 0.0, 150.0, 2)),
            "dr_sr_non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5),), (Fit("binwise"),)),
            ),
        },
        "ttbar": {
            "split": Split("n_jets", (1.5, 2.5, 22.5)),
            "fake_factors": Binned("pt_2", ((20.0, 32.58, 35.33, 38.91, 43.42, 49.0, 57.78, 75.19, 150.0), (20.0, 31.76, 34.05, 36.4, 39.38, 43.09, 48.0, 54.75, 64.68, 84.09, 150.0)), (Fit("smoothed", 26.0), Fit("smoothed", 26.0)), Equipopulated((8, 10), 20.0, 150.0, 2)),
            "non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5), (-0.5, 0.5, 9.5, 10.5, 11.5)), (Fit("binwise"), Fit("binwise"))),
                Binned("pt_1", ((25.0, 42.79, 52.55, 64.96, 83.4, 150.0), (25.0, 40.94, 47.62, 55.66, 65.04, 77.9, 98.35, 150.0)), (Fit("smoothed", 15.0, binwise_left=1), Fit("smoothed", 15.0, binwise_left=1)), Equipopulated((5, 7), 25.0, 150.0, 2)),
                Binned("met", ((0.0, 32.21, 50.21, 67.65, 91.42, 150.0), (0.0, 28.65, 42.41, 54.78, 68.92, 83.65, 104.78, 150.0)), (Fit("smoothed", 25.0), Fit("smoothed", 25.0)), Equipopulated((5, 7), 0.0, 150.0, 2)),
                Binned("mt_tot", ((20.0, 108.74, 132.94, 154.39, 185.23, 250.0), (20.0, 98.17, 118.52, 135.91, 152.69, 173.1, 199.56, 250.0)), (Fit("smoothed", 25.0), Fit("smoothed", 25.0)), Equipopulated((5, 7), 20.0, 250.0, 2)),
                Binned("iso_1", ((0.0, 5e-05, 0.006241, 0.011143, 0.019004, 0.034094, 0.15), (0.0, 5e-05, 0.004722, 0.007917, 0.011763, 0.017188, 0.025944, 0.040469, 0.15)), (Fit("smoothed", 0.02, binwise_left=1), Fit("smoothed", 0.02, binwise_left=1)), Equipopulated((5, 7), 5e-05, 0.15, 6, add_left=(0.0,))),
            ),
        },
        "process_fractions": {"split": Split("n_jets", (-0.5, 2.5, 22.5)), "binned": Binned("mt_1", ((0.0, 41.06, 70.0), (0.0, 28.6, 51.46, 70.0)), (), Equipopulated((2, 3), 0.0, 70.0, 2))},
    },
    "mt": {
        "QCD": {
            "split": Split("n_jets", (1.5, 22.5)),
            "fake_factors": Binned("pt_2", ((30.0, 33.53, 38.0, 44.89, 58.39, 150.0),), (Fit("smoothed", 20.0),), Equipopulated((6,), 30.0, 150.0, 2)),
            "non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5),), (Fit("binwise"),)),
                Binned("pt_1", ((32.0, 36.28, 41.52, 49.02, 59.75, 76.2, 120.0),), (Fit("smoothed", 30.0, binwise_left=1),), Equipopulated((6,), 32.0, 120.0, 2)),
                Binned("jpt_1", ((30.0, 43.61, 53.05, 61.9, 72.26, 83.42, 98.1, 118.52, 150.0),), (Fit("smoothed", 50.0),), Equipopulated((8,), 30.0, 150.0, 2)),
                Binned("met", ((0.0, 12.85, 20.01, 27.48, 35.58, 45.71, 58.81, 80.1, 130.0),), (Fit("smoothed", 40.0),), Equipopulated((8,), 0.0, 130.0, 2)),
                Binned("mt_tot", ((0.0, 53.81, 72.81, 86.11, 98.67, 112.88, 130.65, 157.81, 250.0),), (Fit("smoothed", 50.0),), Equipopulated((8,), 0.0, 250.0, 2)),
                Binned("mass_2", ((0.0, 0.2, 0.5483, 0.7031, 0.8369, 0.9468, 1.0645, 1.1865, 1.3359, 2.0),), (Fit("smoothed", 0.3, binwise_left=1),), Equipopulated((8,), 0.2, 2.0, 4, add_left=(0.0,))),
                Binned("iso_1", ((0.0, 5e-05, 0.009049, 0.01609, 0.025246, 0.037576, 0.055187, 0.075584, 0.106164, 0.15),), (Fit("binwise"),), Equipopulated((8,), 5e-05, 0.15, 6, add_left=(0.0,))),
            ),
            "dr_sr": Binned("pt_tautau", ((0.0, 29.85, 45.64, 59.12, 72.92, 86.63, 101.85, 120.21, 150.0),), (Fit("smoothed", 25.0, binwise_right=1),), Equipopulated((8,), 0.0, 150.0, 2)),
            "dr_sr_non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5),), (Fit("binwise"),)),
            ),
        },
        "ttbar": {
            "split": Split("n_jets", (1.5, 2.5, 23.5)),
            "fake_factors": Binned("pt_2", ((30.0, 31.93, 33.79, 36.32, 39.17, 42.61, 46.79, 52.79, 62.15, 80.43, 150.0), (30.0, 31.46, 33.25, 35.23, 37.44, 39.85, 42.98, 46.63, 51.11, 57.35, 67.65, 86.64, 150.0)), (Fit("smoothed", 12.0), Fit("smoothed", 12.0)), Equipopulated((10, 12), 30.0, 150.0, 2)),
            "non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5), (-0.5, 0.5, 9.5, 10.5, 11.5)), (Fit("binwise"), Fit("binwise"))),
                Binned("pt_1", ((32.0, 38.47, 46.24, 55.11, 66.76, 83.24, 120.0), (32.0, 37.31, 42.96, 49.0, 55.75, 64.14, 74.71, 90.17, 120.0)), (Fit("smoothed", 30.0, binwise_left=1), Fit("smoothed", 30.0, binwise_left=1)), Equipopulated((6, 8), 32.0, 120.0, 2)),
                Binned("jpt_1", ((30.0, 49.34, 61.53, 73.82, 87.31, 106.17, 150.0), (30.0, 57.64, 68.51, 78.32, 88.63, 99.02, 111.88, 127.82, 150.0)), (Fit("smoothed", 20.0), Fit("smoothed", 20.0)), Equipopulated((6, 8), 30.0, 150.0, 2)),
                Binned("met", ((0.0, 29.4, 44.35, 58.2, 73.32, 93.37, 130.0), (0.0, 26.7, 39.15, 50.28, 61.26, 73.0, 87.06, 104.52, 130.0)), (Fit("smoothed", 30.0), Fit("smoothed", 25.0)), Equipopulated((6, 8), 0.0, 130.0, 2)),
                Binned("mt_tot", ((0.0, 97.55, 120.62, 139.62, 158.83, 187.11, 250.0), (0.0, 89.59, 110.01, 125.19, 139.91, 155.13, 173.56, 198.42, 250.0)), (Fit("smoothed", 30.0), Fit("smoothed", 25.0)), Equipopulated((6, 8), 0.0, 250.0, 2)),
                Binned("mass_2", ((0.0, 0.2, 0.6309, 0.8228, 0.9814, 1.126, 1.3066, 2.0), (0.0, 0.2, 0.5498, 0.7056, 0.8301, 0.936, 1.0469, 1.1787, 1.3291, 2.0)), (Fit("smoothed", 0.2, binwise_left=1), Fit("smoothed", 0.15, binwise_left=1)), Equipopulated((6, 8), 0.2, 2.0, 4, add_left=(0.0,))),
                Binned("iso_1", ((0.0, 5e-05, 0.007391, 0.013446, 0.021728, 0.034618, 0.061761, 0.15), (0.0, 5e-05, 0.006266, 0.010457, 0.01553, 0.022521, 0.031821, 0.045844, 0.072362, 0.15)), (Fit("smoothed", 0.03, binwise_left=1), Fit("smoothed", 0.03, binwise_left=1)), Equipopulated((6, 8), 5e-05, 0.15, 6, add_left=(0.0,))),
            ),
        },
        "process_fractions": {"split": Split("n_jets", (-0.5, 2.5, 22.5)), "binned": Binned("mt_1", ((0.0, 20.21, 39.44, 55.84, 70.0), (0.0, 28.12, 51.32, 70.0)), (), Equipopulated((4, 3), 0.0, 70.0, 2))},
    },
    "tt": {
        "QCD": {
            "split": Split("n_jets", (1.5, 22.5)),
            "fake_factors": Binned("pt_1", ((40.0, 49.95, 56.5, 64.33, 75.37, 92.07, 150.0),), (Fit("smoothed", 12.0),), Equipopulated((6,), 40.0, 150.0, 2)),
            "non_closures": (
                Binned("tau_decaymode_1", ((-0.5, 0.5, 9.5, 10.5, 11.5),), (Fit("binwise"),)),
                Binned("pt_2", ((20.0, 41.64, 43.4, 45.48, 48.39, 52.58, 60.91, 150.0),), (Fit("smoothed", 13.0, binwise_left=1),), Equipopulated((7,), 20.0, 150.0, 2)),
                Binned("met", ((0.0, 13.31, 19.52, 26.17, 33.1, 41.72, 55.62, 175.0),), (Fit("smoothed", 20.0, binwise_left=3),), Equipopulated((7,), 0.0, 175.0, 2)),
                Binned("mt_tot", ((0.0, 91.22, 111.65, 127.56, 143.86, 168.31, 250.0),), (Fit("smoothed", 10.0),), Equipopulated((6,), 0.0, 250.0, 2)),
                Binned("pt_vis", ((0.0, 23.09, 38.86, 56.47, 72.87, 89.55, 111.13, 250.0),), (Fit("smoothed", 25.0),), Equipopulated((7,), 0.0, 250.0, 2)),
                Binned("mass_1", ((0.0, 0.2, 0.66, 0.87, 1.06, 1.26, 2.0),), (Fit("smoothed", 0.3, binwise_left=1),), Equipopulated((5,), 0.2, 2.0, 2, add_left=(0.0,))),
                Binned("mass_2", ((0.0, 0.2, 0.61, 0.81, 0.99, 1.2, 2.0),), (Fit("smoothed", 0.4, binwise_left=1),), Equipopulated((5,), 0.2, 2.0, 2, add_left=(0.0,))),
            ),
            "dr_sr": Binned("pt_tautau", ((0.0, 13.37, 19.57, 24.22, 28.83, 32.87, 36.89, 40.58, 44.29, 48.1, 51.79, 55.48, 59.18, 63.17, 67.0, 71.11, 75.39, 80.05, 84.94, 90.05, 95.44, 101.85, 109.8, 118.98, 130.9, 150.0),), (Fit("smoothed", 25.0),), Equipopulated((25,), 0.0, 150.0, 2)),
            "dr_sr_non_closures": (
                Binned("tau_decaymode_1", ((-0.5, 0.5, 9.5, 10.5, 11.5),), (Fit("binwise"),)),
            ),
        },
        "QCD_subleading": {
            "split": Split("n_jets", (1.5, 22.5)),
            "fake_factors": Binned("pt_2", ((40.0, 41.95, 44.2, 46.98, 51.18, 58.89, 150.0),), (Fit("smoothed", 15.0),), Equipopulated((6,), 40.0, 150.0, 2)),
            "non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5),), (Fit("binwise"),)),
                Binned("pt_1", ((32.0, 49.79, 56.35, 64.33, 75.14, 92.15, 150.0),), (Fit("smoothed", 20.0),), Equipopulated((6,), 32.0, 150.0, 2)),
                Binned("met", ((0.0, 14.4, 21.67, 29.47, 38.81, 53.07, 175.0),), (Fit("smoothed", 20.0, binwise_left=3),), Equipopulated((6,), 0.0, 175.0, 2)),
                Binned("mt_tot", ((0.0, 91.22, 111.65, 127.56, 143.86, 168.31, 250.0),), (Fit("smoothed", 30.0),), Equipopulated((6,), 0.0, 250.0, 2)),
                Binned("pt_vis", ((0.0, 25.82, 44.88, 64.58, 84.37, 106.16, 250.0),), (Fit("smoothed", 25.0),), Equipopulated((6,), 0.0, 250.0, 2)),
                Binned("mass_2", ((0.0, 0.2, 0.61, 0.81, 0.99, 1.2, 2.0),), (Fit("smoothed", 0.4, binwise_left=1),), Equipopulated((5,), 0.2, 2.0, 2, add_left=(0.0,))),
                Binned("mass_1", ((0.0, 0.2, 0.66, 0.87, 1.06, 1.26, 2.0),), (Fit("smoothed", 0.3, binwise_left=1),), Equipopulated((5,), 0.2, 2.0, 2, add_left=(0.0,))),
            ),
            "dr_sr": Binned("pt_tautau", ((0.0, 15.37, 22.33, 27.87, 33.09, 37.7, 42.32, 47.01, 51.68, 56.43, 61.12, 66.05, 70.92, 76.35, 82.3, 88.45, 95.62, 103.69, 113.55, 127.29, 150.0),), (Fit("smoothed", 20.0),), Equipopulated((20,), 0.0, 150.0, 2)),
            "dr_sr_non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5),), (Fit("binwise"),)),
            ),
        },
        "ttbar": {
            "split": Split("n_jets", (1.5, 2.5, 23.5)),
            "fake_factors": Binned("pt_1", ((40.0, 60.78, 81.71, 150.0), (40.0, 56.57, 69.07, 89.77, 150.0)), (Fit("smoothed", 12.0), Fit("smoothed", 12.0)), Equipopulated((3, 4), 40.0, 150.0, 2)),
            "non_closures": (
                Binned("tau_decaymode_1", ((-0.5, 0.5, 9.5, 10.5, 11.5), (-0.5, 0.5, 9.5, 10.5, 11.5)), (Fit("binwise"), Fit("binwise"))),
                Binned("pt_2", ((20.0, 46.31, 53.25, 150.0), (20.0, 44.39, 51.81, 62.72, 150.0)), (Fit("smoothed", 20.0, binwise_left=1), Fit("smoothed", 20.0, binwise_left=1)), Equipopulated((3, 4), 20.0, 150.0, 2)),
                Binned("met", ((0.0, 46.03, 88.9, 175.0), (0.0, 42.46, 65.81, 96.41, 175.0)), (Fit("smoothed", 20.0), Fit("smoothed", 20.0)), Equipopulated((3, 4), 0.0, 175.0, 2)),
                Binned("mt_tot", ((0.0, 137.21, 175.25, 250.0), (0.0, 127.39, 155.56, 193.15, 250.0)), (Fit("smoothed", 20.0), Fit("smoothed", 25.0)), Equipopulated((3, 4), 0.0, 250.0, 2)),
                Binned("pt_vis", ((0.0, 55.36, 94.09, 250.0), (0.0, 49.37, 77.78, 106.79, 250.0)), (Fit("smoothed", 25.0), Fit("smoothed", 25.0)), Equipopulated((3, 4), 0.0, 250.0, 2)),
                Binned("mass_1", ((0.0, 0.2, 0.8, 1.08, 2.0), (0.0, 0.2, 0.69, 0.97, 1.22, 2.0)), (Fit("smoothed", 0.4, binwise_left=1), Fit("smoothed", 0.4, binwise_left=1)), Equipopulated((3, 4), 0.2, 2.0, 2, add_left=(0.0,))),
                Binned("mass_2", ((0.0, 0.2, 0.79, 1.02, 2.0), (0.0, 0.2, 0.7, 0.91, 1.16, 2.0)), (Fit("smoothed", 0.27, binwise_left=1), Fit("smoothed", 0.25, binwise_left=1)), Equipopulated((3, 4), 0.2, 2.0, 2, add_left=(0.0,))),
            ),
        },
        "ttbar_subleading": {
            "split": Split("n_jets", (1.5, 2.5, 23.5)),
            "fake_factors": Binned("pt_2", ((40.0, 45.09, 53.97, 150.0), (40.0, 44.0, 49.44, 59.23, 150.0)), (Fit("smoothed", 12.0), Fit("smoothed", 12.0)), Equipopulated((3, 4), 40.0, 150.0, 2)),
            "non_closures": (
                Binned("tau_decaymode_2", ((-0.5, 0.5, 9.5, 10.5, 11.5), (-0.5, 0.5, 9.5, 10.5, 11.5)), (Fit("binwise"), Fit("binwise"))),
                Binned("pt_1", ((32.0, 63.71, 81.04, 150.0), (32.0, 57.79, 74.14, 93.84, 150.0)), (Fit("smoothed", 20.0), Fit("smoothed", 20.0)), Equipopulated((3, 4), 32.0, 150.0, 2)),
                Binned("met", ((0.0, 46.03, 88.9, 175.0), (0.0, 42.46, 65.81, 96.41, 175.0)), (Fit("smoothed", 15.0), Fit("smoothed", 15.0)), Equipopulated((3, 4), 0.0, 175.0, 2)),
                Binned("mt_tot", ((0.0, 137.21, 175.25, 250.0), (0.0, 127.39, 155.56, 193.15, 250.0)), (Fit("smoothed", 20.0), Fit("smoothed", 25.0)), Equipopulated((3, 4), 0.0, 250.0, 2)),
                Binned("pt_vis", ((0.0, 55.36, 94.09, 250.0), (0.0, 49.37, 77.78, 106.79, 250.0)), (Fit("smoothed", 25.0), Fit("smoothed", 15.0)), Equipopulated((3, 4), 0.0, 250.0, 2)),
                Binned("mass_2", ((0.0, 0.2, 0.79, 1.02, 2.0), (0.0, 0.2, 0.7, 0.91, 1.16, 2.0)), (Fit("smoothed", 0.27, binwise_left=1), Fit("smoothed", 0.25, binwise_left=1)), Equipopulated((3, 4), 0.2, 2.0, 2, add_left=(0.0,))),
                Binned("mass_1", ((0.0, 0.2, 0.8, 1.08, 2.0), (0.0, 0.2, 0.69, 0.97, 1.22, 2.0)), (Fit("smoothed", 0.3, binwise_left=1), Fit("smoothed", 0.3, binwise_left=1)), Equipopulated((3, 4), 0.2, 2.0, 2, add_left=(0.0,))),
            ),
        },
        "process_fractions": {"split": Split("n_jets", (-0.5, 2.5, 22.5)), "binned": Binned("m_vis", ((15.0, 94.56, 130.51, 200.0), (15.0, 87.21, 127.26, 200.0)), (), Equipopulated((3, 3), 15.0, 200.0, 2))},
        "process_fractions_subleading": {"split": Split("n_jets", (-0.5, 2.5, 22.5)), "binned": Binned("m_vis", ((15.0, 94.56, 130.51, 200.0), (15.0, 87.24, 127.28, 200.0)), (), Equipopulated((3, 3), 15.0, 200.0, 2))},
    },
}
